### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Oisavictor** [TOBECHI-GH/Web-ecom-8#1]
**Kindly confirm** the following from our meeting held earlier:
1. **Project Name:** Customyz

2. **Details:** 
Customyz is an online or ecommerce website that seeks to help products and services get delivered to its customers promptly, It is also aimed at improving the business sales and coverage by leveraging on the ecommerce technology.

3. **Tasks:**
- Create a beautiful frontend or welcome page that would be attractive to client/customers.
- Create a robust and security hardening backend to protect the privacy of it clients and also it database.
- Test run and fix any bugs

4. **Timeline:**
- Week 1 - _Come up with a **project and it's description*_ - 1st to 7th October,2020.
- Week 2 - _Work on **task 1:** Creating and deploying the frontend_ - 8th to 15th October, 2020.
- Week 3 - _Work on **task 2:** Creating and deploying the backend_ - 16th to 23rd October, 2020. 
- Week 4 - _Work on **task 3:** Testing, running and merging to the main branch. And Finial deployment of the completed project to the cloud.

5. **Individual Responsibilties:**
This is to be assigned to individual contributors and needed by by TTL.

### I hope this is a summary of our discussion and could be shared with the team!. Right?

**Comment by TOBECHI-GH** [comment]
It should be shared with the group
