### ISSUE TITLE
To create a landing page

### ISSUE THREAD

**Issue by TOBECHI-GH** [TOBECHI-GH/Web-ecom-8#2]
To create a landing page

**Comment by TOBECHI-GH** [comment]
Work in progress

**Comment by Oisavictor** [comment]
@TOBECHI-GH what is your progress on the landing page? https://github.com/TOBECHI-GH/Web-ecom-8/projects/1#card-46900571

**Comment by rabsonj** [comment]
> @TOBECHI-GH what is your progress on the landing page? https://github.com/TOBECHI-GH/Web-ecom-8/projects/1#card-46900571

I implemented everything that was suggested for the landing page
