### ISSUE TITLE
To create a client page

### ISSUE THREAD

**Issue by TOBECHI-GH** [TOBECHI-GH/Web-ecom-8#4]
To create a landing page

**Comment by Oisavictor** [comment]
@Simret how far have you gone with the client page?

**Comment by Simret** [comment]
> @Simret how far have you gone with the client page?

@Oisavictor I have managed to work on the basic layout of the client page, I will be adding the lines/borders on the tables today

**Comment by Oisavictor** [comment]
@Simret okay nice
